// Generated by CoffeeScript 1.4.0
(function() {
  var HoursLibcal, init, root, weeklyhours;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.hours = [];

  weeklyhours = (function() {

    function weeklyhours() {
      this.currentlyOpen = currentlyOpen;
      this.status = status;
      this.dates[366] = [
        {
          'date': {
            "": [
              {
                'day': "",
                'from': "",
                'to': ""
              }
            ]
          }
        }
      ];
    }

    return weeklyhours;

  })();

  HoursLibcal = (function() {

    function HoursLibcal(name, category, phone, email, address1, address2, tmz) {
      this.name = name;
      this.category = category;
      this.phone = phone;
      this.email = email;
      this.address1 = address1;
      this.address2 = address2;
      this.tmz = tmz;
    }

    return HoursLibcal;

  })();

  init = function() {
    $.getJSON('http://api3.libcal.com/api_hours_grid.php?iid=1287&format=json&weeks=52&callback=?', function(data) {
      var address1, address2, category, contacts, currOpenTime, currentlyOpen, d, day, email, i, name, phone, tmz, weekday, _i, _ref;
      d = new Date();
      day = d.getDay();
      weekday = new Array(7);
      weekday[0] = "Sunday";
      weekday[1] = "Monday";
      weekday[2] = "Tuesday";
      weekday[3] = "Wednesday";
      weekday[4] = "Thursday";
      weekday[5] = "Friday";
      weekday[6] = "Saturday";
      for (i = _i = 0, _ref = data.locations.length - 1; _i <= _ref; i = _i += 1) {
        name = data.locations[i].name;
        category = data.locations[i].category;
        contacts = data.locations[i].contact;
        phone = contacts.substring(0, contacts.indexOf(";")).trim();
        contacts = contacts.substring(contacts.indexOf(";") + 1).trim();
        email = contacts.substring(0, contacts.indexOf(";")).trim();
        contacts = contacts.substring(contacts.indexOf(";") + 1).trim();
        tmz = contacts.substring(0, contacts.indexOf(";")).toUpperCase().trim();
        contacts = contacts.substring(contacts.indexOf(";") + 1).trim();
        address1 = contacts.substring(0, contacts.indexOf(";") + 1).trim();
        contacts = contacts.substring(contacts.indexOf(";") + 1).trim();
        address2 = contacts.trim();
        currentlyOpen = data.locations[i].weeks[0][weekday[day]].times.currently_open ? "OPEN" : "CLOSED";
        currOpenTime = data.locations[i].weeks[0][weekday[day]].times.status;
        //if (currOpenTime === "open") {
        //  alert("" + currOpenTime);
        //}
        root.hours[i] = new HoursLibcal(name, category, phone, email, address1, address2, tmz);
      }
    });
  };

  init();
  alert(""+root.hours[0].name);
}).call(this);
